name: arlyn culwick
favicon: null
layout_spectrum: 0.6453527121338993
typography_spectrum: 0.708087666425854
title: arlyn culwick
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9339842749759555
  lightness: 0.7680083208251745
  saturation: 0.393797991797328
  rhythmicContrast: 0.1290566106326878
purpose: []
