name: arlyn culwick
favicon: null
layout_spectrum: 0.89647
typography_spectrum: 0.12872
title: arlyn culwick
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#6e6e6e'
    - '#383838'
    - '#8a8a8a'
    - '#c6c6c6'
  brandStrength: 0
  lightness: 0.7680083208251745
  saturation: 0.393797991797328
  rhythmicContrast: 0.75
purpose: []
